### ISSUE TITLE
Support additional DNS providers

### ISSUE THREAD

**Issue by kelseyhightower** [kelseyhightower/kube-cert-manager#1]
Currently the only supported DNS provider is Google Cloud DNS. Based on demand we should consider refactoring the DNS backend to support multiple providers such as Amazon's Route 53.

**Comment by kelseyhightower** [comment]
In the short term lets focus on making the code base rock solid and flush out the design. The focus right now is on code quality and documentation. The `kube-cert-manager` is much a tool for others to learn from as it is a tool for managing certificates.

**Comment by falschparker82** [comment]
Documenting a complementary effort for posterity, could be borrowed from:

https://github.com/xenolf/lego/tree/master/providers/dns

If you're accepting pull requests, let me know!

**Comment by kelseyhightower** [comment]
@falschparker82 Those are awesome by the way. I chose to go with exec based plugins to avoid carrying that stuff in tree, but I'll continue to recommend people leverage code found there when creating dns plugins for `kube-cert-manager`

**Comment by kelseyhightower** [comment]
At this point I'm going to consider this done now that `kube-cert-manager` support dns based plugins.
