### ISSUE TITLE
RFI: kube restclient vs golang http+json

### ISSUE THREAD

**Issue by huggsboson** [kelseyhightower/kube-cert-manager#10]
Your goals for the project include:

> Demonstrate how to build custom Kubernetes controllers.
> Demonstrate how to use Kubernetes Third Party Resources.
> Demonstrate how to interact with the Kubernetes API (watches, reconciliation, etc).

I built a similar thing using thirdpartyresources internally at Box for using our internal CA / pki setup.  I notice that you basically built your own HTTP client vs using kube restclient. I have the restclient basically working, except for one issue around de-serialization which I have hacked around. I'm curious if you avoided using the built-in restclient for any specific reasons other than expediency. 

I'd love to be aligned with the "one-true-way" to do this so I don't inflict work on myself or some other poor soul if they decide to evolve the restclient in the future.

**Comment by kelseyhightower** [comment]
I just favor the lightness of the HTTP API. Once the official client slims down I may start using it.
