### ISSUE TITLE
Please state project status in Readme

### ISSUE THREAD

**Issue by dominikschulz** [kelseyhightower/kube-cert-manager#12]
This repo looks like it's on low maintenance, which is fine. It also clearly states it's goals, which is great.

However it may leave the impression of providing more than it actually does. There is a number of issues as well as some PRs open without much action.

Would you be so kind a to clearly state the current state of this repo/project in the readme? E.g. using http://www.repostatus.org/ or some textual explaination.

Thanks!

**Comment by luna-duclos** [comment]
Perhaps refering to PalmStoneGames/kube-cert-manager at this point would be a good call ? It was initially based on this repo, but has been rewritten to use xenolf/lego to support most dns providers around, it supports ingress objects and actively deals with issues and PRs in a timely fashion.

**Comment by tribou** [comment]
@kelseyhightower would you approve of adding  a message at the top of your README to direct people to PalmStoneGames/kube-cert-manager?

**Comment by kelseyhightower** [comment]
I'll add a section pointing people to popular forks of this project.

**Comment by kelseyhightower** [comment]
I've added a popular forks section.
