### ISSUE TITLE
Handle different namespaces

### ISSUE THREAD

**Issue by dereulenspiegel** [kelseyhightower/kube-cert-manager#22]
Hi,

kube-cert-manager was a great help getting our platform setup. Now I wanted to setup a playground for my developers. So I created a new namespace (including resource quotas), deployed kube-cert-manager in it and create a certificate specification. Strangely enough, the new kube-cert-manager deployment in my playground namespace started issuing certificates for the certificate specifications in my default namespace, ignoring the certificate specification in my playground namespace.
Is there a way to tell kube-cert-manager which namespace to use? If not, would that be a desirable feature? In the end I would like to have a playground with TLS terminating ingress (nginx based) for my developers, so they can go crazy on their 20% projects.

**Comment by whereisaaron** [comment]
@dereulenspiegel there is a [fork of this project](https://github.com/PalmStoneGames/kube-cert-manager) that has both namespace and `class` label filters (analogous to the Ingress `class` annotation). This allows you to [target instances of kube-cert-manager](https://github.com/PalmStoneGames/kube-cert-manager/blob/master/docs/deployment-arguments.md) by namespace or, by project/client/environment, or by the dns-01 DNS API account. Each instance can target one, multiple, or all namespaces, and within those namespace target a specified `class` of Ingress and Certificate resources.

That fork doesn't support the dns-exec plugins/scripts any more, but instead uses the [kube-lego](https://github.com/jetstack/kube-lego) library instead which has out-of-box support for a large number of DNS APIs. This means it can also be used for http-01 challenges. It creates certificates for both Certificate and Ingress resources, and the namespace and label filters work for both. That fork recently added [support for SAN certificates](https://github.com/PalmStoneGames/kube-cert-manager/pull/46), with multiple different domain names per certificate. Sample RBAC security permission for `kube-cert-manager` are provided.

You could either use that fork, or port those features back to this project.

**Comment by kelseyhightower** [comment]
This was merged.
