### ISSUE TITLE
Document cert-reloading without specific application support

### ISSUE THREAD

**Issue by colemickens** [kelseyhightower/kube-cert-manager#5]
In the example/documentation you use an application specially built to expect rolling certs.

Is there an alternative to this? Is there a way to describe a Pod such that it is automatically restarted when one of the Secrets it consumes is changed/updated? (Knowing that it may be less gracefully and elegant than what you are already showing, but possibly more useable for non-specialized applications?)

**Comment by kelseyhightower** [comment]
@colemickens Today the kubelet will update the certificates in place, but it's up to the application to reload the certs from disk after that. I'm sure there is an open issue on the Kubernetes repository for a feature like this, if not maybe we should file one?

**Comment by colemickens** [comment]
I can't find any issue about automatically restarting containers/pods when a Secret is updated to support legacy applications that don't watch the secret with inotify.

I filed: https://github.com/kubernetes/kubernetes/issues/29761

I'll go ahead and close this for now.
