### ISSUE TITLE
Document GCE Ingress Interoperability

### ISSUE THREAD

**Issue by dominikschulz** [kelseyhightower/kube-cert-manager#6]
Please document if or how it is possible to use these Certificates to configure an HTTPS or TLS GCE Loadbalancer.

**Comment by colemickens** [comment]
As a starting point... I believe one could follow this: https://github.com/kubernetes/contrib/tree/master/ingress/controllers/gce#tls since the cert/key in the Secret correspond to the expected names for a Ingress TLS secret. (though I don't think it's going to auto-update)

**Comment by kelseyhightower** [comment]
Update the docs.
