### ISSUE TITLE
Handle subdomains

### ISSUE THREAD

**Issue by erikgrinaker** [kelseyhightower/kube-cert-manager#9]
kube-cert-manager does not seem to handle subdomains. When creating a certificate resource with `domain: test.domain.com`, kube-cert-manager just repeats `lookup test.domain.com on 10.27.240.10:53: no such host`, even though the DNS pointer `test.domain.com` exists. Creating a certificate for `domain: domain.com` works as expected.

**Comment by luna-duclos** [comment]
What's the status on this ? Is this supposed to work, does it work some other way ?

**Comment by kelseyhightower** [comment]
This was fix in #14
